node scaledeployment.js namespace=$1 deploymentname=init-tls-secret replicas=3
node scaledeployment.js namespace=$1 deploymentname=kuberay-operator replicas=1
node scaledeployment.js namespace=$1 deploymentname=milvus-writable replicas=1
node scaledeployment.js namespace=$1 deploymentname=ml-model-service replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-admin-ui replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-ambassador replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-api-gateway replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-apps-manager replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-argo-server replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-argo-workflow-controller replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-auth-ui replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-connector-plugin-jdbc replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-connector-plugin-web-v2 replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-connectors replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-connectors-backend replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-fusion-admin replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-fusion-indexing replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-insights replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-job-config replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-job-launcher replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-job-rest-server replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-kafka-exporter replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-lwai-gateway replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-mysql replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-pm-ui replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-query-pipeline replicas=2
node scaledeployment.js namespace=$1 deploymentname=$1-rules-ui replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-solr-exporter replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-templating replicas=1
node scaledeployment.js namespace=$1 deploymentname=$1-webapps replicas=2
node scaledeployment.js namespace=$1 deploymentname=seldon-controller-manager replicas=1
node scaledeployment.js namespace=$1 deploymentname=selenium-hub replicas=1
node scaledeployment.js namespace=$1 deploymentname=selenium-node-chrome replicas=2

node scaledeployment.js namespace=$1 statefulsetname=$1-async-parsing replicas=1
node scaledeployment.js namespace=$1 statefulsetname=$1-classic-rest-service replicas=1
node scaledeployment.js namespace=$1 statefulsetname=$1-kafka replicas=3
node scaledeployment.js namespace=$1 statefulsetname=$1-solr replicas=3
node scaledeployment.js namespace=$1 statefulsetname=$1-zookeeper replicas=3
